// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWBCsBs5FE014hvxZs-Yvrpr1_aMHjSgA',
    appId: '1:511764833232:web:a6eabe3e83a5e04fe64fd5',
    messagingSenderId: '511764833232',
    projectId: 'movies-app-b1e4c',
    authDomain: 'movies-app-b1e4c.firebaseapp.com',
    storageBucket: 'movies-app-b1e4c.firebasestorage.app',
    measurementId: 'G-8CJ0JC9VZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOlCIcxg1cx-A33RV53XtVuVxe7bMbNNs',
    appId: '1:511764833232:android:936d0d25ce731b9be64fd5',
    messagingSenderId: '511764833232',
    projectId: 'movies-app-b1e4c',
    storageBucket: 'movies-app-b1e4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1BGV6OwYOLdlkruBN9_ycs4ozLvitX3E',
    appId: '1:511764833232:ios:22c5f961183f54c6e64fd5',
    messagingSenderId: '511764833232',
    projectId: 'movies-app-b1e4c',
    storageBucket: 'movies-app-b1e4c.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1BGV6OwYOLdlkruBN9_ycs4ozLvitX3E',
    appId: '1:511764833232:ios:22c5f961183f54c6e64fd5',
    messagingSenderId: '511764833232',
    projectId: 'movies-app-b1e4c',
    storageBucket: 'movies-app-b1e4c.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWBCsBs5FE014hvxZs-Yvrpr1_aMHjSgA',
    appId: '1:511764833232:web:31f583048c7e433ae64fd5',
    messagingSenderId: '511764833232',
    projectId: 'movies-app-b1e4c',
    authDomain: 'movies-app-b1e4c.firebaseapp.com',
    storageBucket: 'movies-app-b1e4c.firebasestorage.app',
    measurementId: 'G-HLP4L85H1Q',
  );
}
